#pragma config(Sensor, dgtl1,  rear_end_detection, sensorTouch)
#pragma config(Motor,  port3,           right_wheels,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           left_wheels,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           r_arm_1,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           r_arm_2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           l_arm_1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           l_arm_2,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	// declare joystick variables
	int stick_left_vert, stick_right_hor;

	//float actual_left_vert = 0, actual_right_hor = 0;
	// declare motor variables
	int l_motors, r_motors;
	int arms;

	while(true){

		// get joystick positions
		stick_left_vert = vexRT[Ch3];
		stick_right_hor = vexRT[Ch1];

		// calculate deadzones
		if(-13 < stick_left_vert && stick_left_vert < 13){
			stick_left_vert = 0;
		}
		if(-13 < stick_right_hor && stick_right_hor < 13){
			stick_right_hor = 0;
		}

		// p-controller (NOT IN USE)
		//actual_left_vert += (stick_left_vert - actual_left_vert) * 0.0003;
		//actual_right_hor += (stick_right_hor - actual_right_hor) * 0.0003;
		//
		// calculate motor speeds
		//l_motors = actual_left_vert + actual_right_hor;
		//r_motors = - actual_left_vert + actual_right_hor;
		l_motors = stick_left_vert + stick_right_hor;
		r_motors = - stick_left_vert + stick_right_hor;

		// Rear end collision detection
		if(SensorValue[rear_end_detection] == 1){
			//l_motors = 128;
			//r_motors = -128;
			motor[left_wheels] = 128;
			motor[right_wheels] = 128;
			wait1Msec(400);
		}

		// set motor speeds
		motor[right_wheels] = r_motors;
		motor[left_wheels] = l_motors;

		// arm motors on button press
		if(vexRT[Btn6U] == 1){
			arms = 128;
		}
		else if(vexRT[Btn6D] == 1){
			arms = -128;
		}
		else{
			arms = 0;
		}
		//motor[r_arm_1] = arms;
		//motor[r_arm_2] = arms;
		//motor[l_arm_1] = - arms;
		//motor[l_arm_2] = - arms;
		motor[r_arm_1] = arms;
		motor[r_arm_2] = arms;
		motor[l_arm_1] = arms;
		motor[l_arm_2] = arms;
	}
}
