#pragma config(Motor,  port3,            ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main(){
	// declare joystick variables
	short left_vert, left_hor;
	// declare motor variables
	short l_motors, r_motors;

	while(true){
		// get joystick positions
		left_vert = vexRT[Ch3];
		left_hor = vexRT[Ch4];
		/*
		if(left_vert < 0){
			left_hor = -left_hor;
		}
		*/
		// calculate deadzones
		if(-13 < left_vert && left_vert < 13){
			left_vert = 0;
		}
		if(-13 < left_hor && left_hor < 13){
			left_hor = 0;
		}
		// calculate motor speeds
		l_motors = left_vert + left_hor;
		r_motors = - left_vert + left_hor;
		// set motor speeds
		motor[port4] = r_motors;
		motor[port3] = l_motors;
	}
}
