#pragma config(Motor,  port1,           lMotor,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           rMotor,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
// http://www.education.rec.ri.cmu.edu/products/cortex_video_trainer/index.html
// For the tutorials!!

motor[lMotor] = 127;
motor[rMotor] = -127;

}
